# Generated by Django 3.0.8 on 2020-07-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
