# Generated by Django 3.0.8 on 2020-07-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Image',
            new_name='image',
        ),
    ]
